name: First-flow
on: push
jobs:   
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: actions version
        uses: actions/checkout@v3
      - name: run npm ci
        run: npm ci
      - name: run npm run lint
        run: npm run lint

  test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: actions version
        uses: actions/checkout@v3
      - name: run npm lint
        run: npm run test
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: actions version
        uses: actions/checkout@v3
      - name: run npm lint
        run: npm run build


    


